### DISCUSSION TITLE
config files: position-based top-level grids

### DISCUSSION THREAD

**Discussion by cymian** [cymian/mouseless#1] [Show and tell]
Here's two config files:

- the first arranges the main grid into recursive cells based on the first character's qwerty key position (like the subgrid's cells are arranged by default), instead of a simple row/column arrangement.
- the second makes the second character position-based as well, but to make this work well on a standard 16:9 aspect ratio, the left hand keys are assigned to the top 3 rows of each cell, and the right hand keys to the bottom 3 rows.

*To load them*
1. Choose **Open config folder** from the mouseless menu for quick access to the config folder
2. Either:
  - Replace the mouse_action_keys and grid_defn fields in your config.yaml file with the mouse_action_keys and grid_defn values here
  - Or save one of the files as config.yaml (will overwrite any customizations you've made)
3. **Restart the program** 

The config editor gui doesn't currently facilitate this sort of customization, but I will add it in a future release, along with ability to switch between config presets.  Enjoy!

```yaml
# important bits for position-based top-level grid
# - (10x3 top-level grid, then 3x10, 30 mouse_action_keys)
# - just replace these fields in your config.yaml to preserve the rest of your config

mouse_action_keys: QWERTYUIOPASDFGHJKL;ZXCVBNM,./
grid_defn:
- border_width: 0.0
  callback: build_cell_strings
  num_cells_x: 10
  num_cells_y: 3
- border_width: 1.0
  callback: build_cell_strings
  num_cells_x: 3
  num_cells_y: 10
- border_width: 0.0
  callback: apply_strings_and_subgrid_to_cells
  num_cells_x: 2
  num_cells_y: 1


# the rest

always_on_subgrid_rgba:
- 1.0
- 1.0
- 1.0
- 0.3
always_show_subgrid: true
app_version: 0.2.0
background_rgba:
- 0.0
- 0.0
- 0.0
- 0.35
classname: AppConfig
font_size_multiplier: 0.5
grid_rgba:
- 0.9
- 1.0
- 1.0
- 1.0
hide_cursor_on_click: true
hide_location: bottom_left
keymap:
  close dialog: AltRight
  cycle click count: null
  cycle mouse action type: null
  cycle mouse button: null
  edit config: Tab
  execute mouse action: Space
  hide overlay: AltRight
  hold for drag: CommandLeft
  hold for move: AltLeft
  hold for right button: CommandRight
  release hold/drag: AltRight
  repeat last mouse action: null
  show overlay: CommandLeft tap
  switch monitor left: ShiftLeft tap
  switch monitor right: ShiftRight tap
  toggle overlay: null
move_duration_ms: 100
move_real_cursor_with_virtual: false
multi_action_timeout_ms: 400
strategy: subgrid
subgrid_dims:
- 8
- 3
subgrid_font_size_multiplier: 0.75
subgrid_mouse_action_keys: QWERUIOPASDFJKL;ZXCVM,./
subgrid_rgba:
- 1.0
- 1.0
- 1.0
- 0.9
subgrid_text_rgba:
- 1.0
- 1.0
- 1.0
- 0.5
tap_threshold_ms: 200
text_rgba:
- 1.0
- 1.0
- 1.0
- 0.65
window_opacity: 1.0

```

```yaml
# important bits for position-based top-level and second-level grid
# - (5x6 grids, 30 mouse_action_keys with left hand chars first so they occupy the top 3 rows, right hand occupies bottom 3)
# - just replace these fields in your config.yaml to preserve the rest of your config

mouse_action_keys: QWERTASDFGZXCVBYUIOPHJKL;NM,./
grid_defn:
- border_width: 0.0
  callback: build_cell_strings
  num_cells_x: 5
  num_cells_y: 6
- border_width: 1.0
  callback: build_cell_strings
  num_cells_x: 5
  num_cells_y: 6
- border_width: 0.0
  callback: apply_strings_and_subgrid_to_cells
  num_cells_x: 2
  num_cells_y: 1


# the rest

always_on_subgrid_rgba:
- 1.0
- 1.0
- 1.0
- 0.3
always_show_subgrid: true
app_version: 0.2.0
background_rgba:
- 0.0
- 0.0
- 0.0
- 0.35
classname: AppConfig
font_size_multiplier: 0.5
grid_rgba:
- 0.9
- 1.0
- 1.0
- 1.0
hide_cursor_on_click: true
hide_location: bottom_left
keymap:
  close dialog: AltRight
  cycle click count: null
  cycle mouse action type: null
  cycle mouse button: null
  edit config: Tab
  execute mouse action: Space
  hide overlay: AltRight
  hold for drag: CommandLeft
  hold for move: AltLeft
  hold for right button: CommandRight
  release hold/drag: AltRight
  repeat last mouse action: null
  show overlay: CommandLeft tap
  switch monitor left: ShiftLeft tap
  switch monitor right: ShiftRight tap
  toggle overlay: null
move_duration_ms: 100
move_real_cursor_with_virtual: false
multi_action_timeout_ms: 400
strategy: subgrid
subgrid_dims:
- 8
- 3
subgrid_font_size_multiplier: 0.75
subgrid_mouse_action_keys: QWERUIOPASDFJKL;ZXCVM,./
subgrid_rgba:
- 1.0
- 1.0
- 1.0
- 0.9
subgrid_text_rgba:
- 1.0
- 1.0
- 1.0
- 0.5
tap_threshold_ms: 200
text_rgba:
- 1.0
- 1.0
- 1.0
- 0.65
window_opacity: 1.0

```
