### DISCUSSION TITLE
User Config Sharing

### DISCUSSION THREAD

**Discussion by sultaz** [cymian/mouseless#73] [Show and tell]
I think it'd be neat if users shared their configs so others can quickly change between different looks without having to dig to deeply into settings.  

I'll start.  My config has large letters with red grid lines so it's easy to see on my laptop screen.

**Comment by sultaz** [comment]
```yaml
always_on_subgrid_rgba:
- 1.0
- 1.0
- 1.0
- 0.3
always_show_subgrid: true
app_version: 0.2.0
background_rgba:
- 0.0
- 0.0
- 0.0
- 0.35
classname: AppConfig
font_size_multiplier: 0.6
grid_defn:
- border_width: 0.0
  callback: build_cell_strings
  num_cells_x: 10
  num_cells_y: 3
- border_width: 1.0
  callback: build_cell_strings
  num_cells_x: 3
  num_cells_y: 10
- border_width: 0.0
  callback: apply_strings_and_subgrid_to_cells
  num_cells_x: 2
  num_cells_y: 1
grid_rgba:
- 1.0
- 0.0
- 0.0
- 1.0
hide_cursor_on_click: false
hide_location: top
keymap:
  close dialog: AltRight
  cycle click count: null
  cycle mouse action type: null
  cycle mouse button: null
  edit config: Tab
  execute mouse action: Space tap
  hide overlay: CommandLeft
  hold for drag: CommandLeft
  hold for move: AltLeft
  hold for right button: CommandRight
  release hold/drag: Space
  repeat last mouse action: null
  show overlay: CommandLeft tap
  switch monitor left: ShiftLeft tap
  switch monitor right: ShiftRight tap
  toggle overlay: null
mouse_action_keys: QWERTYUIOPASDFGHJKL;ZXCVBNM,./
move_duration_ms: 100
move_real_cursor_with_virtual: false
multi_action_timeout_ms: 400
strategy: subgrid
subgrid_dims:
- 8
- 3
subgrid_font_size_multiplier: 1.0
subgrid_mouse_action_keys: QWERUIOPASDFJKL;ZXCVM,./
subgrid_rgba:
- 1.0
- 0.0
- 0.0
- 1.0
subgrid_text_rgba:
- 1.0
- 1.0
- 1.0
- 1.0
tap_threshold_ms: 200
text_rgba:
- 1.0
- 1.0
- 1.0
- 1.0
window_opacity: 0.9
```

**Comment by cymian** [comment]
nice @sultaz, thank you for this 🙏 love to see it!!

if you put the file contents between two lines of triple back quotes (```) it formats it as `code`, which is helpful to avoid bullet points and the like, I went ahead and did this on your comment 👍

screenshots are nice too, if you'd like to share!  i realize now i should add some to my post 😅

thanks again!

**Comment by Nima-shahnazipour** [comment]
@croian I believe I’ve found the ideal layout for people who type with all ten fingers, keeping their fingers consistently on the keyboard. Specifically, their left index finger always rests on the F key, and their right index finger always rests on the J key.

![CleanShot 2024-12-27 at 03 09 25@2x](https://github.com/user-attachments/assets/29956963-3a9e-462f-99a7-2a1d94c07b96)


you can easily move the cursor where ever you want without thinking.


```yaml

app_version: 0.2.2
behavior_configs:
- hide_cursor_on_click: false
  hide_location: bottom_left
  move_duration_ms: 100
  move_real_cursor_with_virtual: true
  multi_action_timeout_ms: 400
  name: main_behavior
  tap_threshold_ms: 200
classname: AppConfig
grid_configs:
- always_show_subgrid: false
  grid_defn:
  - border_width: 0.0
    callback: build_cell_strings
    num_cells_x: 11
    num_cells_y: 1
  - border_width: 1.0
    callback: build_cell_strings
    num_cells_x: 1
    num_cells_y: 11
  - border_width: 0.0
    callback: apply_strings_and_subgrid_to_cells
    num_cells_x: 2
    num_cells_y: 1
  mouse_action_keys: asdfghjkl;'
  name: full_alpha
  strategy: subgrid
  subgrid_dims:
  - 10
  - 3
  subgrid_mouse_action_keys: qwertyuiopasdfghjkl;zxcvbnm,./
- always_show_subgrid: false
  grid_defn:
  - border_width: 0.0
    callback: build_cell_strings
    num_cells_x: 1
    num_cells_y: 26
  - border_width: 1.0
    callback: build_cell_strings
    num_cells_x: 26
    num_cells_y: 1
  - border_width: 0.0
    callback: apply_strings_and_subgrid_to_cells
    num_cells_x: 2
    num_cells_y: 1
  mouse_action_keys: ABCDEFGHIJKLMNOPQRSTUVWXYZ
  name: vertical_alpha
  strategy: subgrid
  subgrid_dims:
  - 4
  - 6
  subgrid_mouse_action_keys: QWERASDFZXCVUIOPJKL;M,./
keymaps:
- entries:
    close dialog: OptionRight
    cycle click count: null
    cycle mouse action type: null
    cycle mouse button: null
    edit config: Tab
    execute mouse action: Space
    hide overlay: OptionRight
    hold for drag: CommandLeft
    hold for move: OptionLeft
    hold for right button: CommandRight
    release hold/drag: OptionRight
    repeat last mouse action: null
    show overlay: CommandLeft tap
    switch monitor left: ShiftLeft tap
    switch monitor right: ShiftRight tap
    toggle overlay: null
  name: mac
monitor_assignments: auto
name: ''
style_configs:
- always_on_subgrid_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.8
  background_rgba:
  - 0.0
  - 0.0
  - 0.0
  - 0.35
  font_size_multiplier: 0.5
  grid_rgba:
  - 0.9
  - 1.0
  - 1.0
  - 0.4
  name: dark_bg
  subgrid_font_size_multiplier: 0.75
  subgrid_rgba:
  - 0.831
  - 0.541
  - 0.365
  - 1.0
  subgrid_text_rgba:
  - 0.831
  - 0.541
  - 0.365
  - 1.0
  text_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.3
  window_opacity: 1.0


```
